[build]
target = "wasm32-unknown-unknown"
rustflags = ["--cfg", "tokio_unstable"]

[target.wasm32-unknown-unknown]
# Requires running `cargo build --release --bin linera-wasm-test-runner` once first.
runner = "target/release/linera-wasm-test-runner"
